In [90]:
import numpy as np
from IPython.display import Image

In [2]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [3]:
print(dp1)
print(dp2)
print(dp3)
print(dp4)

{'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
{'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
{'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
{'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}


#### Creating a manual classifier

In [4]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 13
    else:
        return 0.33

In [5]:
predict(dp1)

0.33

In [6]:
predict(dp2)

0.33

In [7]:
predict(dp3)

13

In [8]:
predict(dp4)

13

#### Creating a linear regression
setting the weights manually. 

In [9]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']

In [10]:
mlpredict(dp4)

13.795310668229778

#### Change this regression data set into a binary classification data set:

In [11]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'broken': 0}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'broken': 0}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'broken': 1}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'broken': 1}

#### Binary classifier:

In [12]:
def predict(dp):
    if dp['maxvibration']> 100:
        return 1
    else:
        return 0

In [13]:
predict(dp1)

0

In [14]:
predict(dp2)

0

In [15]:
predict(dp3)

1

In [16]:
predict(dp4)

1

#### Change the regression model to a logistic regression model:

In [17]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))

In [18]:
w1 = 0.30
w2 = 0
w3 = 0
w4 = 13/3412.0

def mlpredict(dp):
    return 1 if sigmoid(w1+w2*dp['maxtemp']+w3*dp['mintemp']+w4*dp['maxvibration']) > 0.7 else 0

In [19]:
mlpredict(dp4)

1

In [20]:
dp1 = {'partno': 100, 'maxtemp': 35, 'mintemp': 35, 'maxvibration': 12, 'asperity': 0.32}
dp2 = {'partno': 101, 'maxtemp': 46, 'mintemp': 35, 'maxvibration': 21, 'asperity': 0.34}
dp3 = {'partno': 130, 'maxtemp': 56, 'mintemp': 46, 'maxvibration': 3412, 'asperity': 12.42}
dp4 = {'partno': 131, 'maxtemp': 58, 'mintemp': 48, 'maxvibration': 3542, 'asperity': 13.43}

In [21]:
dp1

{'partno': 100,
 'maxtemp': 35,
 'mintemp': 35,
 'maxvibration': 12,
 'asperity': 0.32}

#### Creating a perceptron neural network from scratch. 

##### Converting dictionary to numpy

Get rid of the labels (key)

In [22]:
x1 = [v for k, v in dp1.items()] 
print(x1)

[100, 35, 35, 12, 0.32]


In [23]:
dp1.items()

dict_items([('partno', 100), ('maxtemp', 35), ('mintemp', 35), ('maxvibration', 12), ('asperity', 0.32)])

Removing parno and asperity

In [24]:
x1 = [v for k, v in dp1.items()][1:-1] 
print(x1)

[35, 35, 12]


Align this array or vector to the size of the weight vector

In [67]:
x1 = np.array([1] + [v for k, v in dp1.items()] [1:-1])
print(x1)

[ 1 35 35 12]


In [68]:
x1 = np.array([1] + [v for k, v in dp1.items()] [1:-1])
x2 = np.array([1] + [v for k, v in dp2.items()] [1:-1])
x3 = np.array([1] + [v for k, v in dp3.items()] [1:-1])
x4 = np.array([1] + [v for k, v in dp4.items()] [1:-1])

In [69]:
x1

array([ 1, 35, 35, 12])

Choosing random weights for layer 1:

In [94]:
#w_layer1 = np.random.rand(4)
w_layer1 = np.array([1,2,3,4])
print(w_layer1)

[1 2 3 4]


Using sigmoid as activation function

In [95]:
def neuron(x):
    return sigmoid(x.dot(w_layer1))

In [96]:
print(neuron(x1))
print(neuron(x2))
print(neuron(x1))
print(neuron(x2))

1.0
1.0
1.0
1.0


Neural Network structure:

![texte](https://d3i71xaburhd42.cloudfront.net/40a17f823b03b455a3ace1e406b2716639fd42bc/3-Figure1-1.png)

Modifying the function to compute in paralell:

In [57]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [113]:
w_layer1 = np.random.rand(4,2)
print(w_layer1)

[[0.71289912 0.65767104]
 [0.65997147 0.02159712]
 [0.6958982  0.22386339]
 [0.79962946 0.69079353]]


In [114]:
def layer1(x):
    return sigmoid(x.dot(w_layer1))

In [115]:
x = np.array([x1,x2,x3,x4])

In [116]:
x

array([[   1,   35,   35,   12],
       [   1,   46,   35,   21],
       [   1,   56,   46, 3412],
       [   1,   58,   48, 3542]])

In [117]:
x.dot(w_layer1)

array([[  57.76389117,   17.5383113 ],
       [  72.2202425 ,   23.99302141],
       [2798.0183328 , 2369.15236006],
       [2904.68190181, 2459.44644037]])

In [118]:
layer1(x)

array([[1.        , 0.99999998],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ]])

Choosing random weights for layer 2:

In [128]:
w_layer2 = np.random.rand(2,1)
print(w_layer2)

[[0.24813614]
 [0.53648856]]


In [129]:
def layer2(x):
    return sigmoid(x.dot(w_layer2))

In [130]:
layer2(layer1(x))

array([[0.68667598],
       [0.68667598],
       [0.68667598],
       [0.68667598]])